### ISSUE TITLE
Center Justify thumbnails on new line?

### ISSUE THREAD

**Issue by YasmeenAlmuhanna** [YasmeenAlmuhanna/yasmeenalmuhanna.com#32]
![image](https://user-images.githubusercontent.com/13010867/63969805-aed73c80-ca70-11e9-9f0e-98effbdf75b9.png)

![image](https://user-images.githubusercontent.com/13010867/63969827-bc8cc200-ca70-11e9-8d1a-4e05665d32cf.png)

**Comment by dmbaker90** [comment]
@YasmeenAlmuhanna I made an update for this, however in order to do this I had to add a fixed size to the tiles and move them out of the grid they were in.  They don't grow/shrink like they used too, but they still adjust when you shrink the screen.

If you don't like it I can roll it back, let me know.
